trigger:
 - master
 - refs/tags/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: GoTool@0
  inputs:
    version: '1.13.6'

- task: Bash@3
  inputs:
    filePath: './ci/install-task.sh'
  condition: eq( variables['Agent.OS'], 'Linux' )

- bash: brew install go-task/tap/go-task
  condition: eq( variables['Agent.OS'], 'Darwin' )

- task: PowerShell@2
  inputs:
    filePath: './ci/install-task.ps1'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: task build:release

- powershell: |
    $tag = "$(Build.SourceBranch)" -replace "refs/tags/", ""  
    echo "##vso[task.setvariable variable=tag;isOutput=true]$tag"
  displayName: Get tag

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_paulvarache'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: $(tag)
    assets: 'dist/**/*'
    assetUploadMode: 'replace'
    addChangeLog: false
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
