trigger:
 - master
 - refs/tags/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      archiveType: tar
      archiveExt: .tar.gz
    mac:
      imageName: 'macos-10.13'
      archiveType: tar
      archiveExt: .tar.gz
    windows:
      imageName: 'vs2017-win2016'
      archiveType: zip
      archiveExt: .zip

pool:
  vmImage: $(imageName)

steps:
- task: GoTool@0
  inputs:
    version: '1.13.6'

- task: UseTaskfile@0
  inputs:
    version: '2.8'

- script: task build:release
  displayName: Build binary

- powershell: |
    $output = task get-output
    echo "##vso[task.setvariable variable=output]$output"
  displayName: Get target output

- powershell: |
    $tag = "$(Build.SourceBranch)" -replace "refs/tags/", ""  
    echo "##vso[task.setvariable variable=tag]$tag"
  displayName: Get tag

- task: CopyFiles@2
  inputs:
    Contents: |
      README.md
      LICENSE
    TargetFolder: 'dist'
  displayName: Copy Readme.md and LICENSE

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: $(archiveType)
    archiveFile: $(Build.ArtifactStagingDirectory)/$(output)$(archiveExt)
    replaceExistingArchive: true
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: Archive

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_paulvarache'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: $(tag)
    assets: '$(Build.ArtifactStagingDirectory)/*'
    assetUploadMode: 'replace'
    addChangeLog: false
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: Release on Github
