version: 2

vars:
  APP_NAME: taskfile_language_server
  HASH: $(git rev-parse --short HEAD)
  VERSION: 0.0.0
  OUTPUT: "{{.APP_NAME}}_{{OS}}_{{ARCH}}"

tasks:

  build:
    sources: ["**/*.go"]
    generates: ["./taskfile_language_server{{exeExt}}"]
    cmds:
      - go build -o taskfile_language_server{{exeExt}}
      - echo "Done"

  build:release:
    cmds:
      - go build -ldflags="-X 'main.BuildVersion={{.VERSION}}' -X 'main.BuildHash={{.HASH}}'" -o ./dist/{{.APP_NAME}}{{exeExt}}
  
  get-output:
    cmds:
      - echo {{.OUTPUT}}
    silent: true
