version: 2

vars:
  APP_NAME: taskfile_language_server
  HASH: $(git rev-parse --short HEAD)
  VERSION: 0.0.0
  OUTPUT: dist/{{.APP_NAME}}_{{OS}}_{{ARCH}}

tasks:

  build:
    sources: ["**/*.go"]
    generates: ["./taskfile-language-server{{exeExt}}"]
    cmds:
      - go build
      - echo "Done"

  build:release:
    cmds:
      - go build -ldflags="-X 'main.BuildVersion={{.VERSION}}' -X 'main.BuildHash={{.HASH}}'" -o {{.OUTPUT}}{{exeExt}}
  
  get-output:
    cmds:
      - echo {{.OUTPUT}}
    silent: true
